# CSE-121710302022- K.Naga Vennela

### 1. [Reversing an Array] 
#### Write a NumPy program to reverse an array


In [4]:
import numpy as np
arr = np.arange(12,38)
print("Original array :\n",arr)
print("Reversed array :\n",arr[::-1])


Original array :
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array :
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


### 2. [Make Border 1] 
#### Write a NumPy program to create a 2d array with 1 on the border and 0 inside


In [6]:
n = int(input())
a1 = np.ones((n,n),dtype="int32")
print("Original array:")
print(a1)
print("1 on the border and 0 inside in the array")
a1[1:-1,1:-1] = 0
print(a1)

5
Original array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on the border and 0 inside in the array
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 3. [Membership Test] 
#### Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


In [17]:
import numpy as np
arr1 = np.arange(0,50,10)
print("Arr1 : ",arr1)
arr2 = [10,40]
print("Arr2 : ",arr2)
print("\nCompare each element of Arr1 and Arr2")
print(np.in1d(arr1,arr2))

Arr1 :  [ 0 10 20 30 40]
Arr2 :  [10, 40]

Compare each element of Arr1 and Arr2
[False  True False False  True]


### 4. [Set Difference] 
#### Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.


In [22]:
import numpy as np
a1 = np.arange(0,100,10)
a2 = np.arange(0,100,20)
print("Array 1 : ",a1)
print("Array 2 : ",a2)
print("\nThe set difference between 2 arrays is :",np.setdiff1d(a1,a2))

Array 1 :  [ 0 10 20 30 40 50 60 70 80 90]
Array 2 :  [ 0 20 40 60 80]

The set difference between 2 arrays is : [10 30 50 70 90]


### 5. [Formation of Diagonal Matrix] 
#### Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.


In [31]:
n = [4,5,6,8]
e = np.diagflat(n)
print(e)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
