### Modules---> predefined , userdefined
1. predefined : math, os, string, random, statistics



### Numpy package:
1. Numerical data
2. Computations on numerics

### Differences b/w Numpy array and List:
1. Less Memory
2. Faster
3. Convenient

In [2]:
import numpy as np

In [9]:
# 1- dimensional array

a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [10]:
# 2- dimensional array
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
print(a1.ndim)
print(a1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [34]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.shape)
print(a2.shape[0])
print(a2.shape[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4
3


In [17]:
a3 = np.array([],dtype="int32")

In [21]:
a3 = np.append(a3,int(input()))
a3

6


array([3, 4, 5, 6])

In [22]:
a3 = np.append(a3,[35,72,45,98])
a3

array([ 3,  4,  5,  6, 35, 72, 45, 98])

### slicing

In [23]:
print(a3[3])

6


In [24]:
print(a1[1][0])

4


In [25]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [26]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [29]:
print(a2[0,0:2])

[1 2]


In [32]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


In [33]:
print(a2[:][:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
print(a2[[0,2],:])

[[1 2 3]
 [7 8 9]]


### Iterate through array:

In [38]:
for row in a2:
    print(row)
print('\n')
list1=[[1,2],[3,4]]
for i in list1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


[1, 2]
[3, 4]


In [40]:
for ele in a2.flat:
    print(ele,end="  ")

1  2  3  4  5  6  7  8  9  10  11  12  

In [41]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Indexing with boolean array


In [42]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [49]:
result = (arr1 % 2 == 0)
result
r1 = (arr1 % 2 == 1)

In [48]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr1[r1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Appending Array

In [51]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [55]:
print(np.append(arr1,arr2).reshape(6,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [56]:
print(np.vstack((arr1,arr2))) #vertical stacking 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [57]:
print(np.hstack((arr1,arr2))) #horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape


In [58]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions
1. zeroes()
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [66]:
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [62]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
f=np.full((2,2),"Vennela")
f

array([['Vennela', 'Vennela'],
       ['Vennela', 'Vennela']], dtype='<U7')

In [69]:
e = np.eye(4,dtype="int32")
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [70]:
# linspace()
l = np.linspace(1,10,5,dtype="int32")
l

array([ 1,  3,  5,  7, 10])

In [81]:
# ravel()
a = np.arange(1,13,2).reshape(2,3)
print(a)
print(np.array(a.flat))
print(e.ravel())

[[ 1  3  5]
 [ 7  9 11]]
[ 1  3  5  7  9 11]
[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]


### Function on array :
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [83]:
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

36
[ 9 27]
[ 8 12 16]


In [86]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [88]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))

6.0
6.0
3.415650255319866


### Mathematical Operations : + , -  , * , / , %


In [99]:
x = np.arange(1,5)
y = np.arange(6,10)
print(x)
print(y)
print(x+y)
print(y-x)
print(x*y)
print(x/y)
print(x%y)

[1 2 3 4]
[6 7 8 9]
[ 7  9 11 13]
[5 5 5 5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]
[1 2 3 4]


### dot()--> Matrix multiplication
### arr1 = m x n
### arr2 = n x l

In [101]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [102]:
# Transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying user-defined functions on array :


In [120]:
list1 = list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [121]:
# 1/(1+1) ----> x/(x+1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95,
 0.9523809523809523]

In [122]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [123]:
# in numpy array
f = np.vectorize(lambda x : x/(x+1))
f(a)


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [124]:
print(a)
b = np.vectorize(lambda x : x+1)
print(b(a).reshape(2,10))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21]]


In [ ]:
# help(np.linalg)
# help(np.random)