### Numpy random

In [6]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

15
0.9031313627386414


In [7]:
# creating n- dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[78 64 97]
[[ 8 27 18  1]
 [83 22 14 18]
 [37 45 60 85]]
[[[84 92]
  [85 55]
  [22 70]
  [96 83]]

 [[21 72]
  [93 11]
  [68 88]
  [ 2 20]]

 [[16  1]
  [34 27]
  [62 29]
  [54 83]]]


In [8]:
# creating n- dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))


0.6177179602156628
[0.5253185  0.51985667 0.29433655]
[[0.36186222 0.52845988 0.82771069]
 [0.20863297 0.54392681 0.85234366]]


In [9]:
a = random.randint(100,size=(3,2)).ravel()
a

array([25, 44,  6, 90, 85, 48])

In [10]:
# single element will be selected
random.choice(a)

48

In [12]:
# for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 1, 4, 3],
       [4, 3, 5, 5],
       [4, 1, 1, 5],
       [1, 2, 5, 3]])

### Pandas

### Creating a Dataframe
1. using 2 dictionaries
2. simple dictionary ---->DataFrame

In [15]:
import pandas as pd
import numpy as np
dict1 = {'a':1, 'b':2 ,'c':3, 'd':4, 'e':5}
dict2 = {'a':5, 'b':6 ,'c':7, 'd':8, 'e':9}
data = {"First":dict1, "Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [18]:
# simple dictionary ---->DataFrame
d1 = {"Name":["venni","vishruthi","jahnavi"], "address":["hyd","adb","vzg"]}
df1 = pd.DataFrame(d1)
df1.index = np.arange(1, len(df1) + 1)
df1

Name address
1      venni     hyd
2  vishruthi     adb
3    jahnavi     vzg

In [19]:
# using Series 
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.6,67.4,34.67,38.6,87.1,50,81])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.60       d
4        5    67.40       e
5        6    34.67       f
6        7    38.60       g
7        8    87.10       h
8        9    50.00       i
9       10    81.00       j

### Selecting the data from the DataFrame
1. loc --> Row and Column labels
2. iloc --> Row and Column index

In [30]:
type(df3)

pandas.core.frame.DataFrame

In [20]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.60
4    67.40
5    34.67
6    38.60
7    87.10
8    50.00
9    81.00
Name: column2, dtype: float64

In [24]:
df3[["column2","column3"]]


column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.60       d
4    67.40       e
5    34.67       f
6    38.60       g
7    87.10       h
8    50.00       i
9    81.00       j

In [28]:
#single column  loc[row index , column]
df3.loc[:,["column2"]]

column2
0    12.23
1    23.34
2    45.30
3    45.60
4    67.40
5    34.67
6    38.60
7    87.10
8    50.00
9    81.00

In [29]:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.60
4        5    67.40
5        6    34.67

In [31]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [32]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [37]:
df3.info()
print(df3.shape)
print(df3.columns)
print(df3.index)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 320.0+ bytes
(10, 3)
Index(['column1', 'column2', 'column3'], dtype='object')
RangeIndex(start=0, stop=10, step=1)


### Viewing data from DataFrame
1. head()
2. tail()
3. sample()

In [44]:
# first 5 rows
n=int(input())
df3.head(n)

2


column1  column2 column3
0        1    12.23       a
1        2    23.34       b

In [40]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [41]:
df3.tail()

column1  column2 column3
5        6    34.67       f
6        7    38.60       g
7        8    87.10       h
8        9    50.00       i
9       10    81.00       j

In [46]:
df3.sample(2)

column1  column2 column3
9       10     81.0       j
3        4     45.6       d

In [48]:
# count --> no. of columns
# mean of col. values ........
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  48.524000
std     3.02765  23.949325
min     1.00000  12.230000
25%     3.25000  35.652500
50%     5.50000  45.450000
75%     7.75000  63.050000
max    10.00000  87.100000

In [52]:
df3 = df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.60     d
4      5   67.40     e
5      6   34.67     f
6      7   38.60     g
7      8   87.10     h
8      9   50.00     i
9     10   81.00     j

In [54]:
 rand_arr = np.random.randint(1,15,4) 
print(rand_arr)

[12 14 13  2]


In [66]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

n = 5
np.argwhere(x==1)[5]

array([10], dtype=int64)